# Generated by Django 4.2.8 on 2023-12-22 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
