# Generated by Django 4.2.8 on 2023-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_operation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("GAME", "Игры"), ("DOLG", "Долг")],
                max_length=300,
                null=True,
            ),
        ),
    ]
