# Generated by Django 4.2.8 on 2023-12-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_operation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Питание", "Food"),
                    ("Развлечения", "Games"),
                    ("Медицина", "Med"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
